language: node_js
node_js:
- '4'
- '6'
env:
  - CXX=g++-4.8
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
notifications:
  slack: busytalk:Y3T1Gp4P83g7EUKR1uA2zNvE
